name: "Run scheduled checks: gradle/groovy formatting"

on:
  workflow_dispatch:

  schedule:
    # 3:13 on Mondays
    - cron: '13 4 * * 1'

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  test:
    name: Check groovy/gradle script formatting compliance
    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/prepare-for-build

      - run: >
          ./gradlew
          -Plucene.spotlessGradleScripts=true
          spotlessGradleScriptsCheck
